language: node_js
node_js:
  - "10"
install:
  - npm install -g codecov istanbul
  - npm install -D mocha istanbul
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov